# Generated by Django 4.1.7 on 2023-02-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TecMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Co_Name', models.CharField(max_length=100)),
                ('Clas1', models.CharField(max_length=30)),
                ('Clas2', models.CharField(max_length=30)),
                ('Sub_Clas1', models.CharField(max_length=30)),
                ('Sub_Clas2', models.CharField(max_length=30)),
                ('Sub_Clas3', models.CharField(max_length=30)),
                ('Sub_Clas4', models.CharField(max_length=30)),
                ('Sub_Clas5', models.CharField(max_length=30)),
                ('No_tec', models.CharField(max_length=2)),
                ('Office', models.CharField(max_length=10)),
                ('Specific', models.TextField()),
                ('Web_Page', models.CharField(max_length=100)),
                ('Cel_Number', models.CharField(max_length=25)),
            ],
        ),
    ]
