# Generated by Django 4.1.7 on 2023-02-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecmembers',
            name='Clas2',
        ),
        migrations.RemoveField(
            model_name='tecmembers',
            name='Sub_Clas5',
        ),
        migrations.AlterField(
            model_name='tecmembers',
            name='Cel_Number',
            field=models.CharField(max_length=30),
        ),
    ]
